### ISSUE TITLE
table 14 update

### ISSUE THREAD

**Issue by ayogasekaram** [pharmaverse/falcon#129]
Following code convention document, table 14 code needs the following updates:

- [x] use `saffl_var` variable argument (no hard coding variables)
- [x] use `pref_term` for `AEBODSYS`
- [x] add `id_var` for `USUBJID`

**Comment by edelarua** [comment]
@ayogasekaram for this table you can use `soc_var` or something similar because there is no mention of "preferred term" in the table title. 

Also, if you implement `id_var` for table 14 can you also propagate the change to any other templates that hard-code `"USUBJID"`? You would have to check for any `tern` functions that use USUBJID, or you could avoid that with a hack and just do `df[["USUBJID"]] <- df[[id_var]]` somewhere before the layout within the function(s).
